# Use an official PHP image as a base image
FROM php:8.1-apache

# Set the working directory inside the container
WORKDIR /var/www/html

# Copy the current directory contents into the container
COPY . /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Enable Apache mod_rewrite (if needed)
RUN a2enmod rewrite

# Expose port 80 to the outside world
EXPOSE 8002

# Start Apache server in the foreground
CMD ["apache2-foreground"]

# docker build .
